### ISSUE TITLE
Build Trigger Log

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLTutorials.jl#174]
!rebuild ode_extras/01-ModelingToolkit.jmd

**Comment by christopher-dG** [comment]
!rebuild ode_extras/01-ModelingToolkit.jmd

It doesn't respond to issues, just issue comments (which is a bit awkward, but at least it's more or less a one-time annoyance).

**Comment by christopher-dG** [comment]
!rebuild ode_extras/01-ModelingToolkit.jmd

**Comment by christopher-dG** [comment]
!rebuild introduction

**Comment by christopher-dG** [comment]
!rebuild introduction

**Comment by ChrisRackauckas** [comment]
that pipeline view is beautiful.

**Comment by ChrisRackauckas** [comment]
!rebuild models

**Comment by ChrisRackauckas** [comment]
it looks like that build had key issues?

**Comment by christopher-dG** [comment]
!rebuild models

The error was:

```
+ git checkout master
error: pathspec 'master' did not match any file(s) known to git.
```

Which is weird, I don't know why checking out master would fail. But I tried to not do the checkout if we're already on the right branch so maybe this will work.

**Comment by christopher-dG** [comment]
I think I might have fixed it, time will tell

**Comment by Vaibhavdixit02** [comment]
@christopher-dG just curious, why did you have to exclude the bayesian pendulum tutorial?

**Comment by ChrisRackauckas** [comment]
that one isn't in the models folder

**Comment by ChrisRackauckas** [comment]
Looks like the issues are just TeX issues

**Comment by christopher-dG** [comment]
`models/06-pendulum_bayesian_inference` is in the exclude list though, so perhaps it can be removed from there since that specific file doesn't actually exist.

**Comment by ChrisRackauckas** [comment]
I moved it to another section IIRC. But if we are using the benchmark computer it might be fine to run.

**Comment by ChrisRackauckas** [comment]
- [ ] introduction
- [ ] models
- [ ] ode_extras
- [ ] type_handling
- [ ] model_inference
- [ ] exercises
- [ ] advanced

**Comment by ChrisRackauckas** [comment]
!rebuild ode_extras

**Comment by ChrisRackauckas** [comment]
!rebuild advanced/03-kolmogorov_equations.jmd

**Comment by ChrisRackauckas** [comment]
!model_inference

**Comment by ChrisRackauckas** [comment]
!rebuild model_inference

**Comment by ChrisRackauckas** [comment]
!rebuild exercises

**Comment by ChrisRackauckas** [comment]
!rebuild ode_extras

**Comment by ChrisRackauckas** [comment]
!rebuild exercises/02-workshop_solutions.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild ode_extras

**Comment by ChrisRackauckas** [comment]
!rebuild ode_extras/03-ode_minmax.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild exercises/02-workshop_solutions.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild exercises/02-workshop_solutions.jmd

**Comment by ChrisRackauckas** [comment]
@christopher-dG is there a reason why ode_extras/03-ode_minmax.jmd never shows up in PRs?

**Comment by christopher-dG** [comment]
Hm, I'm not sure. It seems like the script just stops after the Julia invocation which ends [here](https://gitlab.com/JuliaGPU/DiffEqTutorials.jl/-/jobs/620072111#L3407)...  whereas other jobs [like this one](https://gitlab.com/JuliaGPU/DiffEqTutorials.jl/-/jobs/620004438#L3566) have a bunch of other commands afterwards as they should. I'll look into that tomorrow.

**Comment by ChrisRackauckas** [comment]
no worries. Thanks!

**Comment by ChrisRackauckas** [comment]
!rebuild exercises/02-workshop_solutions.md

**Comment by ChrisRackauckas** [comment]
!rebuild exercises/02-workshop_solutions.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild exercises/02-workshop_solutions.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild exercises/02-workshop_solutions.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild ode_extras/03-ode_minmax.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild model_inference

**Comment by ChrisRackauckas** [comment]
!rebuild advanced

**Comment by ChrisRackauckas** [comment]
!rebuild exercises

**Comment by ChrisRackauckas** [comment]
!rebuild exercises/02-workshop_solutions.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild DiffEqUncertainty

**Comment by SebastianM-C** [comment]
Oh, I think I forgot the other example (with the more complicated equations). I'll add it now. At least we can see if the Henon-Heiles one is ok.

**Comment by ChrisRackauckas** [comment]
!rebuild DiffEqUncertainty

**Comment by ChrisRackauckas** [comment]
!rebuild DiffEqUncertainty

**Comment by ChrisRackauckas** [comment]
!rebuild DiffEqUncertainty

**Comment by ChrisRackauckas** [comment]
!rebuild DiffEqUncertainty

**Comment by ChrisRackauckas** [comment]
!rebuild DiffEqUncertainty

**Comment by ChrisRackauckas** [comment]
!rebuild DiffEqUncertainty

**Comment by ChrisRackauckas** [comment]
!rebuild models/05-kepler_problem.html

**Comment by ChrisRackauckas** [comment]
!rebuild models/08-spiking_neural_systems.jmd

**Comment by ChrisRackauckas** [comment]
!rebuild models/08-spiking_neural_systems.jmd
