### ISSUE TITLE
Does tutorial "Optimizing diffeq code" need revision due to change in Julia internals?

### ISSUE THREAD

**Issue by KZiemian** [SciML/SciMLTutorials.jl#277]
I check examples of optimizing adding of matrices presented in it and find that in Julia 1.4 code A + B + C is basically as good as you can get. This is not what this tutorial suggest to me.

In fact, tests from 1 to 5 allocate this same amount of memory (7.63 MiB), with `test2(...)` being 1.5 slowest than `test(...)`. Also `test8!(...)` while allocating only 32 bytes is incredible slow, around 2 times slower than `test(...)`. This [GitHub issue](https://github.com/JuliaLang/julia/issues/35914) explore problem with `map!` apparently losing 50% of speed from Julia 1.0 to 1.4.

You can find my benchmark for adding matrices [here](https://discourse.julialang.org/t/which-is-the-most-efficient-way-to-add-matrices-arrays-in-julia-1-x/39602/8).

**Comment by ChrisRackauckas** [comment]
It can still matter if you do it in a loop since the GC pauses can be significant and `@benchmark` ignores that by GCing between rounds, but yes, this part is much less of an issue than it used to be, and `map!` is... that's sad.

**Comment by ChrisRackauckas** [comment]
Moved to DiffEqDocs
