### ISSUE TITLE
weaving produces errors in 08-spiking_neural_systems.jmd

### ISSUE THREAD

**Issue by danielmk** [SciML/SciMLTutorials.jl#325]
I realized that Weave.jl produced errors on #322 in 08-spiking_neural_system.jmd which I cannot track down. When I run the .ipynb in my Jupyter no errors occur but the weave just doesn't work on my end. Any ideas? I'm not very experienced with Weave.jl

**Comment by ChrisRackauckas** [comment]
The issue is DataStructures v0.18. We need to dig in and find out the versioning issue for the Models.

@devmotion just in case you know what in https://github.com/SciML/SciMLTutorials.jl/blob/master/tutorials/models/Project.toml might be problematic.

**Comment by devmotion** [comment]
DiffEqBiological is the culprit: version 4.3 is only compatible with DataStructures 0.17 (https://github.com/SciML/Catalyst.jl/blob/cdd9606070250a0e571d0a80f26d5458ba4d460d/Project.toml#L23) and the compat section does not allow Catalyst >= 5

**Comment by devmotion** [comment]
Another problem is NeuralNetDiffEq 1.6 which depends on CuArrays which in turn only supports DataStructures 0.17. This could be fixed by updating to NeuralPDE >= 2 + CUDA.

**Comment by devmotion** [comment]
I'm able to use DataStructures 0.18 with these two changes (DiffEqBiological -> Catalyst >= 5 and NeuralNetDiffEq -> NeuralPDE >= 2).

**Comment by ChrisRackauckas** [comment]
Oh yes, those two changes should be made. I guess CompatHelper didn't catch those because of the renames. Let's get those all swapped out and then use the rebuild command.

**Comment by ChrisRackauckas** [comment]
Regenerated in https://github.com/SciML/SciMLTutorials.jl/pull/327 . Looks like that worked. Thanks for pointing it out!
