### ISSUE TITLE
No more Pkg.Display?

### ISSUE THREAD

**Issue by sdwfrost** [SciML/SciMLTutorials.jl#377]
In the [code for generating the footer](https://github.com/SciML/SciMLTutorials.jl/blob/1ca51b590a0a8f3b4e16b479bc9a6842a03c4f76/src/SciMLTutorials.jl#L97):

```julia
pkgs = Pkg.Display.status(Pkg.API.Context(), use_as_api=true);
```

`Pkg.Display` doesn't seem to exist any more.

**Comment by ChrisRackauckas** [comment]
Oh? What's the replacement?

**Comment by sdwfrost** [comment]
I haven't found it yet...

**Comment by ChrisRackauckas** [comment]
Apparently the solution is in https://github.com/JuliaLang/Pkg.jl/pull/1621
