### ISSUE TITLE
add jump tutorials

### ISSUE THREAD

**Issue by isaacsas** [SciML/SciMLTutorials.jl#431]
Would be good to add some non-spatial jump tutorials too showing off how to use the newer MassActionJumps and the general lower-level interface. Event handling is something that gets asked about enough that some examples would be good to have.

**Comment by ChrisRackauckas** [comment]
We can discuss specific tutorials as needed, but now with per-package docs these should probably go to the JumpProcesses or Catalyst docs, unless it's a bigger demonstration or a cross-package workflow demonstration.

**Comment by isaacsas** [comment]
Yeah, moving the spatial tutorial to JumpProcesses has been on my TODO also.
