### ISSUE TITLE
README should say how to download tutorial notebooks

### ISSUE THREAD

**Issue by mberkowitz** [SciML/SciMLTutorials.jl#444]
This README should explain how to download the  tutorial notebooks in runnable form.
 Currently it says:
  _] add https://github.com/SciML/SciMLTutorials.jl
  using SciMLTutorials;  SciMLTutorials.open_notebooks()_
which fails as the directory _SciMLTutorials.jl/notebooks_ does not exist.
I found the compiled notebooks in another github repo, in SciMLTutorialsOutput/notebook.
The README should at least mention this source; better would be to have a link/command to make a local download.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLTutorials.jl/pull/445 solves this.

**Comment by mberkowitz** [comment]
thanks!
