### ISSUE TITLE
ModelingToolkit tutorial errors

### ISSUE THREAD

**Issue by cobac** [SciML/SciMLTutorials.jl#503]
There are multiple code chunks that evaluate to errors in [the ModelingToolkit.jl tutorial](https://tutorials.sciml.ai/html/ode_extras/01-ModelingToolkit.html). I am not familiar with the ecosystem yet to know if it's because the interface has changed or what is going on.

**Comment by ChrisRackauckas** [comment]
Yeah that one is so old we might need to delete it and start from scratch. I need to do a pass through some of the symbolic tutorials.

**Comment by cobac** [comment]
Maybe it's a good idea to flag them as out-of-date or not weave them in the meantime?

**Comment by YingboMa** [comment]
Do you mind to open a PR?

**Comment by cobac** [comment]
I'd be happy to. I'm just not sure if it's better to flag them or not weave them directly, or which ones are the _symbolic tutorials_ in plural that Chris refereed to 😄 .

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLTutorials.jl/pull/505
