### ISSUE TITLE
DiffEqBiological packages outdated

### ISSUE THREAD

**Issue by rlars** [SciML/SciMLTutorials.jl#509]
The tutorials https://tutorials.sciml.ai/html/models/03-diffeqbio_I_introduction.html and following are outdated. They still refer to DiffEqBiological instead of Catalyst.
On my system, I started to fix the tutorials and I came across several issues, some of which I could fix. I will try to create a comprehensive list of errors if you are interested in keeping these tutorials. In my opinion this would make sense, because the examples in the Catalyst docs are by far not as detailed.

**Comment by rlars** [comment]
This is what I came up so far:
https://github.com/rlars/SciMLTutorials.jl/commit/366b2c4da585e88ef50cb22755d7ce700578a967

**Comment by ChrisRackauckas** [comment]
@isaacsas did you update these?

**Comment by isaacsas** [comment]
These should probably just be removed; the first two tutorials are basically covered in Catalyst doc tutorials, as is a basic example of bifurcations with BifurcationKit. The steady-state calculations via homotopycontinuation are not currently supported in an explicit way, but I think @TorkelE had been looking into it for adding to ModelingToolkit in general. 

@rlars what do you feel is missing from the current Catalyst tutorials?

**Comment by isaacsas** [comment]
It would be nice if we could easily sync the Catalyst doc tutorials into Weave ones here somehow to allow a Notebook version. @ChrisRackauckas is there any tooling for syncing from there here or vice-versa?

**Comment by ChrisRackauckas** [comment]
Such tooling doesn't exist, but I'm trying to get it built.

**Comment by isaacsas** [comment]
I guess we could convert the Catalyst tutorials to Weave markdown ones here, and then just link to them in the Catalyst docs.

**Comment by rlars** [comment]
> @rlars what do you feel is missing from the current Catalyst tutorials?
Ah, I see, I compared https://catalyst.sciml.ai/dev/tutorials/basic_examples/ to the DiffEqBiological tutorials. If I look at https://catalyst.sciml.ai/dev/tutorials/using_catalyst/, I can find what I missed.

**Comment by ChrisRackauckas** [comment]
Tutorials moved to Catalyst
