### ISSUE TITLE
Unable to weave tutorials

### ISSUE THREAD

**Issue by AlexanderSimWS** [SciML/SciMLTutorials.jl#536]
I'm able to add the package but I get this problem when I run "SciMLTutorials.open_notebooks()":

ERROR: IOError: readdir("DiffEqUncertainty"): no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error
   @ ./libuv.jl:97 [inlined]
 [2] readdir(dir::String; join::Bool, sort::Bool)
   @ Base.Filesystem ./file.jl:865
 [3] readdir
   @ ./file.jl:858 [inlined]
 [4] weave_folder(folder::String, build_list::Tuple{Symbol})
   @ SciMLTutorials ~/.julia/packages/SciMLTutorials/97ktD/src/SciMLTutorials.jl:69
 [5] weave_all(build_list::Tuple{Symbol})
   @ SciMLTutorials ~/.julia/packages/SciMLTutorials/97ktD/src/SciMLTutorials.jl:64
 [6] open_notebooks()
   @ SciMLTutorials ~/.julia/packages/SciMLTutorials/97ktD/src/SciMLTutorials.jl:131
 [7] top-level scope
   @ REPL[3]:1

How do I fix this?

**Comment by fernikalo** [comment]
Hi,
I have same problems even trying to open the Jupiter notebooks using the following commands:

using Pkg
pkg"add https://github.com/SciML/SciMLTutorials.jl"
using SciMLTutorials
SciMLTutorials.open_notebooks()

**Comment by doswellf** [comment]
Hi All, 

At first I used the instructions from the top of the tutorials web page to get started. Using either of Julia 1.6.3  or Julia 1.8.x did not work. The first version is too old, the second version is too new. Using Julia version 1.7.3 was the silver bullet.

My experience is that the success of your weaves depends on the correct Julia version. When I use Julia 1.7.3 and follow the instructions on 
[https://tutorials.sciml.ai/stable/](url) 

then things work fine.  I can weave markdown, notebooks and pdf files too.

To get julia 1.7.3 Install juliaup and then install 1.7.3 using juliaup.

Then even the instructions for Contributing at the bottom work if I do not enter the second line
`cd(joinpath(dirname(pathof(SciMLTutorials)), ".."))`

The instructions for contributing may work under 1.7.3 with the `cd(joinpath...)` statement, but I haven't re-tried that yet.

**Comment by ChrisRackauckas** [comment]
I fixed it up to be a lot more automated. See the new directions in https://github.com/SciML/SciMLTutorials.jl#interactive-notebooks . They should be added to the doc websites shortly.

**Comment by doswellf** [comment]
Thanks!

Will try this out with Julia 1.6.3, 1.7.3 and 1.8.2. When experimenting, 
I found that using docker or linux containers to completely isolate the 
versions prevented brain fog.
